#' This function manipulates output data generated by SimBM and SimOU function.
#'
#'See SImBM and SimOU for format of output data. manip manipulates the data by taking the absolute value of phylogenetic independent contrast and then calculates the median of all contrast generated for each node of the tree. This function allows you you to see the split of the data. It also calculates the pvalue and effect size between the simulated phylogenetic independent contrast and emperical values for PIC taken directly from data passes as the 'means' attribute.
#'
#' @param PIC_values of class 'matrix'; matrix of PIC values, output from simBM/simOU
#' @param n interger for number of simulations
#' @param tree of class 'phylo'
#' @param means vector of class 'numeric' with continuous trait values for each species
#'
#' @return matrix of pvalues and effect sizes
#'
#' @example
#' x <- simOU(trait_data, my_tree, n, tip_names)
#' my_tree <- sample_tree.RData
#' n = 10
#' trait_data <- c(40,57,29,31,31,32,53,40,41,31)
#' results <- manip(x, n, my_tree, trait_data)
#'
#'
#'  @export



manip <- function(PIC_values, n, tree, means) {
  holder = 1
  medians <- numeric(max(tree$Nnode))
  stddev <- numeric(max(tree$Nnode))

  for (x in 1:(tree$Nnode*n)){
    PIC_values[x] <- abs(PIC_values[x])

    if (x%% 10 == 0){
      medians[holder] <- median(PIC_values[(x-9):x])
      stddev[holder] <- sd(PIC_values[(x-9):x])
      holder= holder+ 1
    }
  }

  #resp1 = results part 1 (median values and standard deviations)
  resp1 <- (cbind(medians = medians,stddev=stddev))

  #calculate PIC values for emperical data
  empPIC <- pic(means, tree)

  pvals <- numeric(max(length(empPIC)))
  esize <- numeric(max(length(empPIC)))

  #calculate pvals and save to vector
  for (row in 1:length(pvals)){
   tempData <- t.test(PIC_values[,row], mu =empPIC[row])
   pvals[row] <- tempData$p.value
  }


  #effect size calculations
  for (row in 1:length(esize)){
    esize[row] <- (abs(resp1[row,1]-empPIC[row]))/resp1[row,2]
  }

  return(cbind(pvals, esize))

}



